#!/bin/sh
LAMP_Install(){
	apt install apache2 -y
	apt install apache2 apache2-utils -y
	apt install lynx -y
	systemctl restart apache2
	apt install chromium-browser -y
	apt install mariadb-server mariadb-client -y
	#Issues with this part here
	#mysql_secure_installation

	apt install php -y
	a2enmod php8.1
	systemctl restart apache2
	cd /var/www/html
	file="phpinfo.php"
	echo "<?php phpinfo(); ?>" > $file
	cat $file
	
}

echo ENSURE YOU ARE A ROOT USER BEFORE USING THIS BASH SCRIPT
echo "Updating system"
apt update -y
 apt upgrade -y
echo "List of tasks available: "
echo "Install LAMP stack (All tools needed to host a website locally) - Enter '1' to install LAMP stack"
echo ""


read -p "Please enter task you would like to be performed: " TASK 
if [ $TASK==1 ]
	then LAMP_Install

fi