#!/bin/sh
LAMP_Install(){
	apt install apache2 -y
	apt install apache2 apache2-utils -y
	apt install lynx -y
	systemctl restart apache2
	apt install chromium-browser -y
	apt install mariadb-server mariadb-client -y
	#Issues with this part here
	#mysql_secure_installation

	apt install php -y
	a2enmod php8.1
	systemctl restart apache2
	cd /var/www/html
	file="phpinfo.php"
	echo "<?php phpinfo(); ?>" > $file
	cat $file
	
}

TREE_DirectoryStructure(){
	apt install tree 
	cd ~/home
	tree


}

echo ENSURE YOU ARE A ROOT USER BEFORE USING THIS BASH SCRIPT
echo "Updating system"
apt update -y
apt upgrade -y
choice = "Y"


while [ $choice=="Y" ]
echo ""
echo ""
echo "List of tasks available: "
echo ""
echo "Install LAMP stack (All tools needed to host a website locally) - Enter 'LAMP' to install LAMP stack"
echo ""
echo "Show directory structure - Enter 'TREE' to install and show directory structure"
echo ""

#This command reads what the user enters and stores it in the value TASK
read -p "Please enter task you would like to be performed: " TASK 
case $TASK in #This command tells the terminal what to do depending on what is entered
"LAMP") LAMP_Install ;;
"TREE") TREE_DirectoryStructure ;;
esac
done